#改为NACOS配置中心管理，通过在线NACOS管理，此处配置仅做参考
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:192.168.0.183}:${DB_PORT:5432}/${DB_NAME:meta_data}?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&stringtype=unspecified
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

