server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.109:5432/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&stringtype=unspecified
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true