server:
  port: 8079
spring:
  #redis相关配置
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:redis}
    #连接超时时间
    timeout: 5000
